# Decision Tree Classification

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Training the Decision Tree Classification model on the Training set

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier1 = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier1.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

## Training the K-NN model on the Training set

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier2 = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier2.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

## Training the SVM model on the Training set

In [ ]:
from sklearn.svm import SVC
classifier3 = SVC(kernel = 'linear', random_state = 0)
classifier3.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

## Training the Naive Bayes model on the Training set

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier4 = GaussianNB()
classifier4.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

## Training the Random Forest Classification model on the Training set

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier5 = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier5.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

## Training the Logistic Regression model on the Training set

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier6 = LogisticRegression(random_state = 0)
classifier6.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

## Training the Kernel SVM model on the Training set

In [ ]:
from sklearn.svm import SVC
classifier7 = SVC(kernel = 'rbf', random_state = 0)
classifier7.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

## Training the XGBRegressor model on the Training set

In [ ]:
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error
#xgboost
classifier8 = XGBRegressor(objective ='reg:linear',
                       colsample_bytree = 0.3, 
                       learning_rate = 0.1,
                       max_depth = 5, 
                       alpha = 10, 
                       random_state=777,
                       n_estimators = 100)
classifier8.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

## Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

dictionary = {}

name = 'Decision Tree Classification'
y_pred = classifier1.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(name)
print(cm)
print(accuracy_score(y_test, y_pred))
print("")
dictionary[name] = accuracy_score(y_test, y_pred)

name = 'K-NN'
y_pred = classifier2.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(name)
print(cm)
print(accuracy_score(y_test, y_pred))
print("")
dictionary[name] = accuracy_score(y_test, y_pred)

name = 'SVM'
y_pred = classifier3.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(name)
print(cm)
print(accuracy_score(y_test, y_pred))
print("")
dictionary[name] = accuracy_score(y_test, y_pred)

name = 'Naive Bayes'
y_pred = classifier4.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(name)
print(cm)
print(accuracy_score(y_test, y_pred))
print("")
dictionary[name] = accuracy_score(y_test, y_pred)

name = 'Random Forest Classification'
y_pred = classifier5.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(name)
print(cm)
print(accuracy_score(y_test, y_pred))
print("")
dictionary[name] = accuracy_score(y_test, y_pred)

name = 'Logistic Regression'
y_pred = classifier6.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(name)
print(cm)
print(accuracy_score(y_test, y_pred))
print("")
dictionary[name] = accuracy_score(y_test, y_pred)

name = 'Kernel SVM'
y_pred = classifier7.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(name)
print(cm)
print(accuracy_score(y_test, y_pred))
print("")
dictionary[name] = accuracy_score(y_test, y_pred)

name = 'XGB Regressor'
y_pred = classifier8.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(name)
print(cm)
print(classifier8.score(xtrain, ytrain) )
print("")
dictionary[name] = accuracy_score(y_test, y_pred)

best_model = max(dictionary, key=dictionary.get)
print("The best choice is:")
print(best_model, "with a score:", dictionary[best_model])

Decision Tree Classification
[[103   4]
 [  3  61]]
0.9590643274853801

K-NN
[[103   4]
 [  5  59]]
0.9473684210526315

SVM
[[102   5]
 [  5  59]]
0.9415204678362573

Naive Bayes
[[99  8]
 [ 2 62]]
0.9415204678362573

Random Forest Classification
[[102   5]
 [  6  58]]
0.935672514619883

Logistic Regression
[[103   4]
 [  5  59]]
0.9473684210526315

Kernel SVM
[[102   5]
 [  3  61]]
0.9532163742690059

The best choice is:
Decision Tree Classification with a score: 0.9590643274853801
